In [1]:
import numpy as np

In [2]:
reservoir_size = 10

In [3]:
W = np.zeros((reservoir_size, reservoir_size))
for i in range(reservoir_size):
    j = (i+1) % reservoir_size
    W[i, j] = 1.0

In [4]:
W

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
W = np.zeros((reservoir_size, reservoir_size))
for i in range(reservoir_size):
    # Connect to 3 forward neighbors
    for offset in range(1, 4):
        j = (i + offset) % reservoir_size
        W[i, j] = 1.0
    # Connect to 3 backward neighbors
    for offset in range(1, 4):
        j = (i - offset) % reservoir_size
        W[i, j] = 1.0

In [6]:
W

array([[0., 1., 1., 1., 0., 0., 0., 1., 1., 1.],
       [1., 0., 1., 1., 1., 0., 0., 0., 1., 1.],
       [1., 1., 0., 1., 1., 1., 0., 0., 0., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 1., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 0., 1., 1., 1.],
       [1., 0., 0., 0., 1., 1., 1., 0., 1., 1.],
       [1., 1., 0., 0., 0., 1., 1., 1., 0., 1.],
       [1., 1., 1., 0., 0., 0., 1., 1., 1., 0.]])

In [ ]:
p = 0.5  # rewiring probability

W = np.zeros((reservoir_size, reservoir_size))
for i in range(reservoir_size):
    for offset in range(1, 4):
        W[i, (i + offset) % reservoir_size] = 1.0
        W[i, (i - offset) % reservoir_size] = 1.0

for i in range(reservoir_size):
    current_connections = np.where(W[i] == 1.0)[0]
    for j in current_connections:
        if np.random.rand() < p:
            W[i, j] = 0.0
            possible_nodes = list(set(range(reservoir_size)) - {i} - set(np.where(W[i] == 1.0)[0]))
            if possible_nodes:
                new_j = np.random.choice(possible_nodes)
                W[i, new_j] = 1.0

In [10]:
W

array([[0., 1., 1., 1., 1., 1., 0., 0., 1., 0.],
       [1., 0., 1., 1., 0., 1., 1., 1., 0., 0.],
       [1., 1., 0., 1., 1., 1., 0., 0., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 1., 0., 1., 1.],
       [0., 1., 1., 1., 1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0., 1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1., 0., 1., 0., 0., 1.],
       [1., 1., 0., 1., 0., 1., 1., 0., 0., 1.],
       [0., 1., 1., 0., 1., 1., 1., 0., 1., 0.]])